baseURL: https://aafu.pages.dev/
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu
languageCode: en-us
build:
  writeStats: true
params:
  title: Nicholas Brana
  author: Nicholas Brana
  description: Nicholas Brana's personal website and portfolio.
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Github Pages](https://www.github.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Nicholas Brana"
    tagline: Cybersecurity Master's Student
    location: "Old Bridge, NJ"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/nbrana129/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/nbrana"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I am a Master's student in Cybersecurity with a passion for technology and a keen interest in penetration testing. I have a strong background in computer science and a deep understanding of cybersecurity principles. My goal is to leverage my skills to contribute to the field of cybersecurity and help organizations protect their digital assets.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Job Title
        dates: 2019 - *Present*
        company: Company Name
        details: |1-
          - Led the migration of Local AD print servers and shared drives to cloud-based Azure for three New York City charter school networks, supporting over 20+ schools.
          - Managed asset inventory and hardware lifecycle for school devices, performing repairs and routine maintenance.
          - Automated Chromebook lifecycle management with Python scripts, significantly reducing operational hours.
          - Provided hands-on IT support, remediating issues with Active Directory, print servers, teacher’s laptops
          - Delivered exceptional client support and reduced downtime through effective troubleshooting and rapid repairs.
          - Conducted hardware QA checks on 500+ laptops and Chromebooks for teacher and student devices and repaired any damage or defects.
      - position: Customer Engineer Intern
        dates: June 2023 - August 2023
        url: "#"
        company: Ricoh USA, Inc.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: M.S. in Cybersecurity
        college: Fordham University
        dates: September 2024 - January 2026
        thesis_title: "#"
        thesis_url: "#"
      - degree: B.S. in Computer Science
        college: Fordham University
        dates: January 2021 - May 2024
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Malware Classification System
        url: "#"
        description: Used ANNs to classify binary PE files as malware or benign over multiple datasets.
      - title: National Cyber Leage Spring 2025 95th Percentile
        url: "#"
        description: Achieved 95th percentile in the National Cyber League Spring 2025 competition, demonstrating advanced skills in cybersecurity challenges. Top category was network traffic analysis.
      - title: Project 3
        url: "#"
        description: Description of the project
      - title: Project 4
        url: "#"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Biking
      - hobby: Astronomy
      - hobby: Reading
